version: "3.8"
services:
  db:
    image: mysql
    container_name: db_myportfolio
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      DATABASE_URL: "mysql://root:@db_docker_symfony:3306/db_dev?serverVersion=5.7"
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_myportfolio
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
  www:
    build: docker/php/test
    container_name: www_myportfolio
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
networks:
  dev:
volumes:
  db-data:
