home:
    path: /
    methods: GET
    controller: App\UserInterface\Controller\HomeController::index

curriculum:
  path: /cv
  methods: GET
  controller: App\UserInterface\Controller\CurriculumController::curriculum

portfolio:
  path: /portfolio
  methods: GET
  controller: App\UserInterface\Controller\PortfolioController::portfolio
