index:
    path: /
    controller: App\Controller\PagesController::index
curriculum:
  path: /cv
  controller: App\Controller\PagesController::curriculum
portfolio:
  path: /portfolio
  controller: App\Controller\PagesController::portfolio
