name: CI with database
on: [push]
jobs:
  build:
    name:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Use docker
        run: docker-compose up -d

      - name: Prepare Database Test
        run: docker-compose exec www sh -c make prepare-test
        env:
          DATABASE_URL: "mysql://root:@db_myportfolio:3306/db_test?serverVersion=5.7"

      - name: Run Tests
        run: docker-compose exec www sh -c make tests
        env:
          DATABASE_URL: "mysql://root:@db_myportfolio:3306/db_test?serverVersion=5.7"



