name: CI with database
on: [push]
jobs:
  build:
    name:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: mysql
          mysql root password: ${{ secrets.RootPassword }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name : Compoer Install
        run : composer install --prefer-dist

      - name: Symfony Cache Clear
        run : php bin/console cache:clear --env=test

      - name: Database Drop
        run: php bin/console doctrine:database:drop --if-exists -f --env=test
        env:
          DATABASE_URL: "mysql://root:@mysql:3306/db_test?serverVersion=5.7"

      - name: Database Create
        run: php bin/console doctrine:database:create --env=test
        env:
          DATABASE_URL: "mysql://root:@mysql:3306/db_test?serverVersion=5.7"

      - name: Database Schema update
        run: php bin/console doctrine:schema:update -f --env=test
        env:
          DATABASE_URL: "mysql://root:@mysql:3306/db_test?serverVersion=5.7"

      - name: Database Load Fixtures
          run: php bin/console doctrine:fixtures:load -n --env=test
          env:
            DATABASE_URL: "mysql://root:@mysql:3306/db_test?serverVersion=5.7"

      - name: Run Tests
          run: bin/phpunit --testsuite unit,integration,system,end_to_end
          env:
            DATABASE_URL: "mysql://root:@mysql:3306/db_test?serverVersion=5.7"



